spring:
  application:
    name: df-kafka-experiment
  kafka:
    bootstrap-servers: localhost:9092 # docker-compose로 띄운 로컬 브로커 엔드포인트
    producer:
      client-id: df-kafka-experiment-producer # 브로커 모니터링 시 구분에 도움되는 ID
      # key/value serializer는 직접 ProducerFactory에서 주입하므로 여기서는 지정하지 않음

ad-clicks:
  producer:
    topic: ad-click-events      # 기본 토픽명 (환경마다 override 가능, 필수 값)
    acks: all                   # 모든 복제본에 쓰기 완료될 때까지 대기
    linger-ms: 20               # 전송 전 모아둘 최대 대기 시간(ms)
    batch-size: 32768           # 배치 전송할 최대 사이즈(바이트)
    compression-type: snappy    # 압축 알고리즘 (gzip, lz4 등으로 교체 가능)
    enable-idempotence: true    # 중복 전송 방지 플래그
  load-test:
    enabled: false              # 기본적으로 자동 부하는 비활성화
    total-events: 0             # 프로필에서 override하여 100000 등으로 사용
    scenario-label: base        # 실행 시 로그에 표기할 시나리오 이름

server:
  port: 8090
